language: python

python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y uuid-runtime

install:
  - pip install -r pip-install-req.txt
  - pip install -r pip-dev-req.txt
  - pip install coveralls

before_script:
  - cp pidman/localsettings.py.sample pidman/localsettings.py
  - echo "SECRET_KEY = '`uuidgen`'" >> pidman/localsettings.py

script:
  - python manage.py test

after_success:
  - coveralls
