language: python

python:
  - "2.7"

install:
  - pip install -r pip-install-req.txt
  - pip install -r pip-dev-req.txt
  - pip install coveralls

before_script:
  - cp pidman/localsettings.py.sample pidman/localsettings.py
  - echo "SECRET_KEY = '$DJANGO_SECRET_KEY'" >> pidman/localsettings.py
  - python manage.py migrate --noinput

script:
  - python manage.py test

after_success:
  - coveralls
