USE persis;

ALTER TABLE auth_group_permissions ADD CONSTRAINT auth_group_permissions_group_id_fkey FOREIGN KEY (group_id) REFERENCES auth_group(id);
ALTER TABLE auth_group_permissions ADD CONSTRAINT auth_group_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES auth_permission(id);
ALTER TABLE auth_message ADD CONSTRAINT auth_message_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user(id);
ALTER TABLE auth_permission ADD CONSTRAINT content_type_id_refs_id_728de91f FOREIGN KEY (content_type_id) REFERENCES django_content_type(id);
ALTER TABLE auth_user_groups ADD CONSTRAINT auth_user_groups_group_id_fkey FOREIGN KEY (group_id) REFERENCES auth_group(id);
ALTER TABLE auth_user_groups ADD CONSTRAINT auth_user_groups_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user(id);
ALTER TABLE auth_user_user_permissions ADD CONSTRAINT auth_user_user_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES auth_permission(id);
ALTER TABLE auth_user_user_permissions ADD CONSTRAINT auth_user_user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user(id);
ALTER TABLE django_admin_log ADD CONSTRAINT content_type_id_refs_id_288599e6 FOREIGN KEY (content_type_id) REFERENCES django_content_type(id);
ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user(id);
ALTER TABLE emory_ldap_emoryldapuserprofile ADD CONSTRAINT emory_ldap_emoryldapuserprofile_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user(id); 
ALTER TABLE linkcheck_link ADD CONSTRAINT linkcheck_link_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES django_content_type(id);
ALTER TABLE linkcheck_link ADD CONSTRAINT linkcheck_link_url_id_fkey FOREIGN KEY (url_id) REFERENCES linkcheck_url(id);
ALTER TABLE pid_domain ADD CONSTRAINT parent_id_refs_id_548a3a632d50978b FOREIGN KEY (parent_id) REFERENCES pid_domain(id);
ALTER TABLE pid_domain ADD CONSTRAINT policy_id_refs_id_6686929444dd5bc7 FOREIGN KEY (policy_id) REFERENCES pid_policy(id);
ALTER TABLE pid_pid ADD CONSTRAINT creator_id_refs_id_2b252a496928159a FOREIGN KEY (creator_id) REFERENCES auth_user(id);
ALTER TABLE pid_pid ADD CONSTRAINT domain_id_refs_id_114baef01f2d1f7d FOREIGN KEY (domain_id) REFERENCES pid_domain(id);
ALTER TABLE pid_pid ADD CONSTRAINT editor_id_refs_id_2b252a496928159a FOREIGN KEY (editor_id) REFERENCES auth_user(id);
ALTER TABLE pid_pid ADD CONSTRAINT ext_system_id_refs_id_272bc5a1ac5d1fa FOREIGN KEY (ext_system_id) REFERENCES pid_extsystem(id);
ALTER TABLE pid_pid ADD CONSTRAINT policy_id_refs_id_1d776576c7b8a649 FOREIGN KEY (policy_id) REFERENCES pid_policy(id);
ALTER TABLE pid_target ADD CONSTRAINT pid_id_refs_id_467b333ec1eefee FOREIGN KEY (pid_id) REFERENCES pid_pid(id);   
ALTER TABLE pid_target ADD CONSTRAINT proxy_id_refs_id_20851e67d63770bb FOREIGN KEY (proxy_id) REFERENCES pid_proxy(id);
ALTER TABLE usage_stats_targetaccesslog ADD CONSTRAINT target_id_refs_id_5a6d9138067c36c0 FOREIGN KEY (target_id) REFERENCES pid_target(id);
